spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop

        show-sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always